WITH
    RENTAL_LIST AS (
        SELECT CAR_ID
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            START_DATE < '2022-12-01'
            AND END_DATE >= '2022-11-01'
    ),

ENABLE_CAR AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE
        C.CAR_ID NOT IN(
            SELECT CAR_ID
            FROM RENTAL_LIST
        )
        AND (
            C.CAR_TYPE = '세단'
            OR C.CAR_TYPE = 'SUV'
        )
),

DISCOUNT_TABLE AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE
        DURATION_TYPE = '30일 이상'
)

SELECT E.CAR_ID, E.CAR_TYPE, ROUND(
        E.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100
    ) AS FEE
FROM
    ENABLE_CAR E
    JOIN DISCOUNT_TABLE D ON E.CAR_TYPE = D.CAR_TYPE
HAVING
    FEE >= 500000
    AND FEE < 2000000
ORDER BY FEE DESC, E.CAR_TYPE ASC, E.CAR_ID DESC;